#cloud-config
users:
  - name: josh
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
write_files:
  - path: /etc/locale.gen
    append: true
    content: |
      en_US.UTF-8 UTF-8
package_update: true
locale: en_US.UTF-8
packages:
  - curl
  - locales
  - ssh-import-id
  - sudo
runcmd:
  - [sudo, -Hu, josh, ssh-import-id, gh:jobrk]
