#cloud-config
users:
  - name: josh
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_import_id:
      - gh:jobrk
package_update: true
locale: en_US.UTF-8
packages:
  - curl
  - locales
runcmd:
  - [locale-gen, en_US.UTF-8]
  - [update-locale, LANG=en_US.UTF-8]
