---
- name: Install alacritty
  tags: ui
  ansible.builtin.command: ~/.cargo/bin/cargo install alacritty
  changed_when: true

- name: Create ~/.config/alacritty if it does not exist
  tags: ui
  ansible.builtin.file:
    path: ~/.config/alacritty
    state: directory
    mode: "0755"

- name: Copy alacritty.yml
  tags: ui
  ansible.builtin.copy:
    src: ../configs/alacritty.yml
    dest: ~/.config/alacritty/alacritty.yml
    mode: "0644"
