---
- name: Check for alacritty (Linux)
  when: ansible_system == 'Linux'
  ansible.builtin.stat:
    path: ~/.cargo/bin/alacritty
  register: alacritty_binary
  tags: rust

- name: Install alacritty via cargo (Linux)
  when: ansible_system == 'Linux' and not alacritty_binary.stat.exists
  ansible.builtin.command: ~/.cargo/bin/cargo install alacritty
  changed_when: true
  tags: rust
