---
- name: Create dotfiles parent directory
  ansible.builtin.file:
    path: "{{ dotfiles_dest | dirname }}"
    state: directory
    mode: "0755"

- name: Clone dotfiles  # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/jobrk/dotfiles
    dest: "{{ dotfiles_dest }}"
    recursive: true

- name: Use SSH for dotfiles pushes
  community.general.git_config:
    name: remote.origin.pushurl
    value: git@github.com:jobrk/dotfiles.git
    scope: local
    repo: "{{ dotfiles_dest }}"

- name: Enable stylua pre-commit hook in nvim config
  community.general.git_config:
    name: core.hooksPath
    value: .githooks
    scope: local
    repo: "{{ dotfiles_dest }}/nvim/.config/nvim"

- name: Stow dotfiles
  ansible.builtin.command: ./install.sh
  args:
    chdir: "{{ dotfiles_dest }}"
  register: dotfiles_stow
  changed_when: "'LINK:' in dotfiles_stow.stderr or 'UNLINK:' in dotfiles_stow.stderr"
