---
- name: Install Iosevka Term Nerd Font (Linux)
  when: ansible_facts['system'] == 'Linux'
  block:
    - name: Create ~/.fonts
      ansible.builtin.file:
        path: ~/.fonts
        state: directory
        mode: "0755"

    - name: Download and unpack IosevkaTerm nerd font
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/IosevkaTerm.tar.xz
        dest: ~/.fonts
        remote_src: true
        creates: ~/.fonts/IosevkaTermNerdFont-Regular.ttf

    - name: Refresh font cache
      ansible.builtin.command: fc-cache -f ~/.fonts
      changed_when: false
