---
- name: Check for Homebrew
  ansible.builtin.stat:
    path: "{{ homebrew_prefix }}/bin/brew"
  register: brew_binary

- name: Install Homebrew
  ansible.builtin.shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  environment:
    NONINTERACTIVE: "1"
  when: not brew_binary.stat.exists
  changed_when: not brew_binary.stat.exists
