---
- name: Add skhd and yabai Homebrew tap
  community.general.homebrew_tap:
    name: koekeishiya/formulae
    state: present

- name: Install skhd and yabai
  community.general.homebrew:
    name:
      - koekeishiya/formulae/skhd
      - koekeishiya/formulae/yabai

- name: Fast key repeat
  community.general.osx_defaults:
    key: KeyRepeat
    type: float
    value: 2.0

- name: Short delay until key repeat
  community.general.osx_defaults:
    key: InitialKeyRepeat
    type: float
    value: 15.0

- name: Disable press-and-hold accent popup (repeat keys instead)
  community.general.osx_defaults:
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
