---
- name: Check for fnm
  ansible.builtin.command: "{{ fnm_executable }} --version"
  register: fnm_check
  changed_when: false
  failed_when: false
  check_mode: false

- name: Download fnm installer
  ansible.builtin.get_url:
    url: https://fnm.vercel.app/install
    dest: ~/.fnm-installer
    mode: "0755"
  when: fnm_check.rc != 0

- name: Install fnm
  ansible.builtin.command: >-
    ~/.fnm-installer --skip-shell
    --install-dir {{ lookup('env', 'HOME') }}/.local/share/fnm
  when: fnm_check.rc != 0
  changed_when: true

- name: Remove fnm installer
  ansible.builtin.file:
    path: ~/.fnm-installer
    state: absent

- name: Symlink fnm into ~/.local/bin (Linux)
  ansible.builtin.file:
    src: "{{ fnm_executable }}"
    dest: ~/.local/bin/fnm
    state: link
  when: ansible_facts['system'] == 'Linux'

- name: Install latest LTS node
  ansible.builtin.command: "{{ fnm_executable }} install --lts --corepack-enabled"
  register: fnm_install
  changed_when: "'already installed' not in fnm_install.stderr"

- name: Find latest LTS node version
  ansible.builtin.command: "{{ fnm_executable }} list-remote --lts --latest"
  register: fnm_latest_lts
  changed_when: false
  check_mode: false

- name: Read default node version
  ansible.builtin.command: "{{ fnm_executable }} default"
  register: fnm_default
  changed_when: false
  failed_when: false
  check_mode: false

- name: Use latest LTS node by default
  ansible.builtin.command: "{{ fnm_executable }} default lts-latest"
  when: >-
    fnm_default.rc != 0 or
    (fnm_default.stdout | trim) !=
    (fnm_latest_lts.stdout | regex_search('v[0-9]+\\.[0-9]+\\.[0-9]+'))
  changed_when: true
