---
- name: Check for fnm
  ansible.builtin.stat:
    path: ~/.local/share/fnm/fnm
  register: fnm_binary

- name: Install fnm
  ansible.builtin.shell: |
    curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
  when: not fnm_binary.stat.exists
  changed_when: not fnm_binary.stat.exists

- name: Install latest LTS node
  ansible.builtin.command: ~/.local/share/fnm/fnm install --lts
  register: fnm_install
  changed_when: "'already installed' not in fnm_install.stderr"
