---
- name: Install tpm  # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    depth: 1

- name: Install tmux plugins
  ansible.builtin.command: ~/.tmux/plugins/tpm/bin/install_plugins
  args:
    creates: ~/.tmux/plugins/tmux-sensible
